name: Lint

on: 
  push:
    branches:
        - 'main'
  pull_request:
    branches:
        - 'feature/**'
    types: [opened, edited]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable