name: Publish

on:
  # Ideally this would be based on the test workflow running
  workflow_run:
    # Only run once testing is complete (success checked later)
    workflows: [Test]
    types: [completed]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Build
        run: |
          poetry build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ secrets.PYPI_PROJECT }}
          password: ${{ secrets.PYPI_TOKEN }}

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Did not publish due to failed tests'