name: TestRunner

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install python environment
        run: |
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest