name: Tests

on:
  # push:
  #   branches:
  #       - 'main'
  pull_request:
    branches:
        - 'main'
    types: [opened, ready_for_review]

jobs:
  test:
    uses: ./.github/workflows/run_tests.yml