name: TestPR

on:
  pull_request:
    branches:
        - 'main'
    types: [opened, ready_for_review]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test workflow
        uses: ./.github/workflows/run_tests.yml