name: Test

on: 
  push:
    branches:
        - 'main'
  pull_request:
    branches:
        - 'main'
    types: [opened, ready_for_review]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install python environment
        run: |
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest