name: TestRelease

on:
  push:
    branches:
        - 'main'

jobs:
  test_release:
    runs-on: ubuntu-latest
    steps:
      - name: Run test workflow
        uses: beancandesign/oswdatamodel/.github/workflows/run_tests.yml